version: "2"
services:
  postgres:
    image: "jkatskuid/docker-postgres-uuid"
    ports:
      - "4321:5432"
    environment:
      POSTGRES_PASSWORD: "cream"
      POSTGRES_USER: "cream"
    volumes: 
      - "./pgdata:/var/lib/postgresql/data"
  redis:
    image: "redis:3.0.7"
    ports:
      - "6543:6379"
    volumes: 
      - "./redis:/data"